# Generated by Django 6.0.6 on 2026-07-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('borrow_created', 'Borrow Request Created'), ('borrow_approved', 'Borrow Request Approved'), ('borrow_rejected', 'Borrow Request Rejected'), ('borrow_cancelled', 'Borrow Request Cancelled'), ('borrow_returned', 'Equipment Returned'), ('equipment_created', 'Equipment Added'), ('equipment_updated', 'Equipment Updated'), ('equipment_deleted', 'Equipment Deleted'), ('staff_approved', 'Staff Account Approved'), ('staff_rejected', 'Staff Account Rejected'), ('profile_updated', 'Profile Updated'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
