# Generated by Django 6.0.6 on 2026-07-15 14:44

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload equipment image (max 5MB, JPG/PNG/GIF/WebP)', null=True, upload_to=dashboard.models.get_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), dashboard.models.validate_image_size]),
        ),
    ]
