# Generated by Django 6.0.6 on 2026-07-15 06:58

import dashboard.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload equipment image (JPEG/PNG, max 2MB)', null=True, upload_to='equipment_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), dashboard.models.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status'], name='dashboard_b_status_e449c5_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['request_date'], name='dashboard_b_request_1dd644_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['user', 'status'], name='dashboard_b_user_id_c898b8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='dashboard_e_status_9e8f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category'], name='dashboard_e_categor_98ca90_idx'),
        ),
    ]
