# Generated by Django 6.0.6 on 2026-07-15 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_equipment_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='dashboard_a_user_id_4bd247_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='dashboard_a_action_70e598_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='dashboard_a_timesta_3a0d49_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='dashboard_a_action_f7e4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='dashboard_a_user_id_15b85a_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['user', 'request_date'], name='dashboard_b_user_id_932623_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status', 'request_date'], name='dashboard_b_status_b98511_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequestitem',
            index=models.Index(fields=['request'], name='dashboard_b_request_80343d_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequestitem',
            index=models.Index(fields=['equipment'], name='dashboard_b_equipme_969e02_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequestitem',
            index=models.Index(fields=['request', 'equipment'], name='dashboard_b_request_1972a9_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='dashboard_e_name_75339c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['quantity_available'], name='dashboard_e_quantit_dcab92_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['quantity_total'], name='dashboard_e_quantit_de94d6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', 'category'], name='dashboard_e_status_e9329b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['request'], name='dashboard_r_request_6769d0_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['staff'], name='dashboard_r_staff_i_0b9c98_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['borrowed_date'], name='dashboard_r_borrowe_f46415_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['return_date'], name='dashboard_r_return__9e92bc_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['due_date'], name='dashboard_r_due_dat_dc693b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['staff', 'borrowed_date'], name='dashboard_r_staff_i_11adda_idx'),
        ),
    ]
